//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string DOB { get; set; }
        public Nullable<long> ClassId { get; set; }
        public Nullable<long> SectionId { get; set; }
        public string Description { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    }
}
