//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSC
    {
        public long Id { get; set; }
        public Nullable<long> TeacherId { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public Nullable<long> Class { get; set; }
        public Nullable<long> Section { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    }
}
